#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/sbin/ecnmarker.uc

get_netdevs() {
	config_get_bool disabled "$1" disabled 0
	[ "$disabled" -eq 0 ] || return 0

	config_get iface "$1" interface
	test -L "/sys/class/net/${iface}" && append netdevs "$iface"
}

service_triggers() {
	procd_add_raw_trigger "interface.*" 2000 /etc/init.d/ecnmarker restart
}

start_service() {
	config_load ecnmarker
	procd_open_instance
	procd_set_param command "$PROG"
	config_foreach get_netdevs interface
	for i in $netdevs; do
		procd_append_param netdev "$i"
	done
	procd_close_instance
}
